version: '3.4'

services:
 sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "appTennisCourt!1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "developer"
    ports:
      - "1433:1433"